<?php

/**
 * Implements hook_menu().
 */
function drupalday_menu() {
  $items['nodejs_form'] = array(
    'title' => 'NodeJS Form',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('drupalday_form'),
    'access callback' => TRUE,
  );

  return $items;
}

/**
 * Form constructor : DrupalDay Form.
 *
 * @param array $form
 * @param array $form_state
 *
 * @return array
 */
function drupalday_form($form, &$form_state) {
  $path = drupal_get_path('module', 'drupalday');
  // Add css in page.
  drupal_add_css($path . '/css/drupalday.css');

  // Create channel by token.
  nodejs_send_content_channel_token('drupalday_form');

  // Form components.
  $form['text'] = array(
    '#type' => 'textfield',
    '#required' => TRUE,
    '#attributes' => array('placeholder' => array('Digite sua mensagem'), 'class' => array('text-drupalday')),
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Send'),
    '#ajax' => array(
      'callback' => 'drupalday_form_ajax_submit'
    ),
  );

  $form['container'] = array(
    '#type' => 'markup',
    '#markup' => '<ul id="mensages-drupalday-form"></ul>',
    '#attached' => array(
      'js' => array($path . '/js/drupalday.js'),
    ),
  );

  return $form;
}

/**
 * Form submit callback : drupalday_form.
 *
 * @see drupalday_form()
 */
function drupalday_form_ajax_submit($form, &$form_state) {
  $text = $form_state['values']['text'];

  // Build message object.
  $message = new stdClass();
  $message->channel = 'drupalday_form';
  $message->callback = 'drupalday';
  $message->data['append_content'] = drupalday_append_content($text);

  // Send message to the content channel.
  nodejs_send_content_channel_message($message);

  // Clear textfield.
  $commands[] = ajax_command_invoke('.text-drupalday', 'val', array(''));

  return array('#type' => 'ajax', '#commands' => $commands);
}

function drupalday_append_content($text) {
  global $user;

  return "<li class=\"drupalday__row\"><span class=\"name\">{$user->name}</span><p class=\"text\">{$text}<p>";
}
